### ISSUE TITLE
[Feature Request] TinyFX Home Assistant support

### ISSUE THREAD

**Issue by darraghbr** [pimoroni/picofx#12]
Clearly a bit of an epic task, but with the release of the TinyFX W it would be amazing to tie it together with a home automation system such as Home Assistant.

In the first instance just being able to run and stop the main script from a home automation web UI would be awesome, but a fully fledged API with each output being controllable would be even better, bonus points if it's accessible from either BLE or WiFi. 

By the looks of things ESPHome is developing RP2040 support, but at this stage seems to suggest only the Raspberry Pi Pico W board itself is supported.

https://github.com/esphome/esphome-docs/blob/current/components/rp2040.rst

**Comment by joeydunlop** [comment]
Actually the tinyfx W board can be flashed as an esphome device only "big" issue is sound which seems is not supported on picow architecture. This requirers some skilled esphome custom component programmer to make it work.

Base ESPhome config here

```yaml
esphome:
  name: tfx
  friendly_name: tfx

e131:
  method: unicast # Or 'multicast' if your network/software prefers it



      
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your key here"

ota:
  - platform: esphome
    password: "your key here"

wifi:
  power_save_mode: NONE # Crucial for I2S audio stability
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Tax Fallback Hotspot"
    password: "your key here"

# The RM2 module uses the RP2040 (Pico W architecture)
rp2040:
  board: rpipicow


switch:
  - platform: gpio
    pin: GPIO21
    name: "AMP Enable"
    id: amp_en
    restore_mode: ALWAYS_ON

output:
  # The 6 Mono FX Channels use the rp2040_pwm platform

  - platform: rp2040_pwm
    pin: GPIO3
    id: fx_out_1
  - platform: rp2040_pwm
    pin: GPIO2
    id: fx_out_2
  - platform: rp2040_pwm
    pin: GPIO4
    id: fx_out_3
  - platform: rp2040_pwm
    pin: GPIO5
    id: fx_out_4
  - platform: rp2040_pwm
    pin: GPIO8
    id: fx_out_5
  - platform: rp2040_pwm
    pin: GPIO9
    id: fx_out_6

  # The onboard Status RGB LED
  - platform: rp2040_pwm
    pin: GPIO13
    id: rgb_red_out
  - platform: rp2040_pwm
    pin: GPIO14
    id: rgb_green_out   
  - platform: rp2040_pwm
    pin: GPIO15
    id: rgb_blue_out

# --- LIGHT ENTITIES ---

light:
  # Individual control for the 6 FX ports
  - platform: monochromatic
    name: "FX Channel 1"
    output: fx_out_1
    default_transition_length: 0.1s
    id: l1   
  - platform: monochromatic
    name: "FX Channel 2"
    output: fx_out_2
    default_transition_length: 0.1s
    id: l2
  - platform: monochromatic
    name: "FX Channel 3"
    output: fx_out_3
    default_transition_length: 0.1s
    id: l3
  - platform: monochromatic
    name: "FX Channel 4"
    output: fx_out_4
    default_transition_length: 0.1s
    id: l4
  - platform: monochromatic
    name: "FX Channel 5"
    output: fx_out_5
    default_transition_length: 0.1s
    id: l5
  - platform: monochromatic
    name: "FX Channel 6"
    output: fx_out_6
    default_transition_length: 0.1s
    id: l6

  # Combined RGB Status LED
  - platform: rgb
    name: "Status LED"
    red: rgb_red_out
    green: rgb_green_out
    blue: rgb_blue_out
    restore_mode: ALWAYS_OFF
    default_transition_length: 0.1s
    id: l7

  - platform: partition
    id: addressable_strip
    name: "Virtual Addressable Strip"
    segments:
      - single_light_id: l1
      - single_light_id: l2
      - single_light_id: l3
      - single_light_id: l4
      - single_light_id: l5
      - single_light_id: l6
    effects:
      - e131:
          universe: 1         # The DMX universe to listen to
          channels: MONO       # Each LED uses 3 channels
```
